# Generated by Django 4.0.4 on 2022-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akbars_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingworkingroom',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время бронирования'),
        ),
    ]
